import type { AttackChain, Evidence, Finding, ScanDetail } from "@/lib/api";
import { riskFromFindings, SEVERITY_ORDER } from "@/lib/severity";
import { chainTitle, formatWhen, prettyClass } from "@/lib/utils";

const SEVERITY_COLORS: Record<string, string> = {
  Critical: "#e5484d",
  High: "#e67a2e",
  Medium: "#d4a017",
  Low: "#8b93a7",
};

const LOGO_SVG = `<svg width="28" height="28" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
  <path d="M23 8 C23 5.5 20 5 16.5 5 C12 5 9 6.5 9 10 C9 15 23 14 23 20 C23 24 19 26 15 26 C11 26 9 25 9 22.5" stroke="#1a1d24" stroke-width="2.4" stroke-linecap="round" fill="none"/>
  <circle cx="23" cy="8" r="2.6" fill="#F2913D"/>
  <circle cx="9" cy="22.5" r="2.6" fill="#1a1d24"/>
</svg>`;

export function buildScanReportHtml(scan: ScanDetail): string {
  const risk = riskFromFindings(scan.findings.map((item) => item.severity_score));
  const when = scan.finished_at ?? scan.started_at;
  const findings = [...scan.findings].sort(
    (a, b) => (SEVERITY_ORDER[b.severity_label] ?? 0) - (SEVERITY_ORDER[a.severity_label] ?? 0),
  );
  const severityOrder = ["Critical", "High", "Medium", "Low"];
  const classRows = Object.entries(scan.summary.by_vuln_class);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>SentinelAPI — API Security Report · scan ${escapeHtml(String(scan.id))}</title>
<style>${REPORT_CSS}</style>
</head>
<body>
  <header class="masthead">
    <div class="brand">
      ${LOGO_SVG}
      <div>
        <p class="wordmark">SentinelAPI</p>
        <h1>SentinelAPI — API Security Report</h1>
      </div>
    </div>
    <p class="meta"><span class="mono">${escapeHtml(scan.target)}</span></p>
    <p class="meta">Scanned ${escapeHtml(formatWhen(when))} · Scan #${escapeHtml(String(scan.id))}</p>
    <p class="advisory">Generated by SentinelAPI · advisory report</p>
  </header>

  <section>
    <h2>Executive summary</h2>
    <div class="summary-grid">
      <div class="score-card">
        <p class="kicker">Overall risk score</p>
        <p class="score-line">
          <span class="hero" style="color:${severityColor(risk.label)}">${escapeHtml(risk.score.toFixed(1))}</span>
          <span class="over">/ 10</span>
          ${badge(risk.label)}
        </p>
        <p class="meta">Total findings: <strong>${escapeHtml(String(scan.summary.total_findings))}</strong></p>
      </div>
      <div>
        <p class="kicker">Severity breakdown</p>
        <table>
          <thead><tr><th>Severity</th><th>Count</th></tr></thead>
          <tbody>
            ${severityOrder
              .map((label) => {
                const count = scan.summary.by_severity[label] ?? 0;
                return `<tr><td>${badge(label)}</td><td class="num">${escapeHtml(String(count))}</td></tr>`;
              })
              .join("")}
          </tbody>
        </table>
      </div>
    </div>
    <p class="posture">${escapeHtml(postureParagraph(scan, risk.score, risk.label))}</p>
  </section>

  <section>
    <h2>Findings by class</h2>
    ${
      classRows.length === 0
        ? `<p class="empty">No vulnerability classes were recorded on this scan.</p>`
        : `<table>
          <thead><tr><th>Class</th><th>Count</th></tr></thead>
          <tbody>
            ${classRows
              .map(
                ([name, count]) =>
                  `<tr><td>${escapeHtml(prettyClass(name))}</td><td class="num">${escapeHtml(String(count))}</td></tr>`,
              )
              .join("")}
          </tbody>
        </table>`
    }
  </section>

  ${renderChains(scan.chains)}

  <section>
    <h2>Detailed findings</h2>
    ${findings.length === 0 ? `<p class="empty">This scan recorded no findings.</p>` : findings.map(renderFinding).join("")}
  </section>

  <footer>
    <p>Ethics: only scan APIs you own or are authorized to test.</p>
    <p>Scan #${escapeHtml(String(scan.id))} · ${escapeHtml(formatWhen(when))} · Advisory report</p>
  </footer>
</body>
</html>`;
}

function renderChains(chains: AttackChain[]): string {
  if (chains.length === 0) return "";
  return `<section>
    <h2>Attack chains</h2>
    ${chains
      .map(
        (chain) => `<article class="block">
      <div class="row">
        <h3>${escapeHtml(chainTitle(chain.id))}</h3>
        ${badge(chain.max_severity_label)}
      </div>
      <p>${escapeHtml(chain.narrative)}</p>
    </article>`,
      )
      .join("")}
  </section>`;
}

function renderFinding(finding: Finding): string {
  const evidence = finding.evidence[0];
  return `<article class="block finding">
    <div class="row">
      ${badge(finding.severity_label)}
      <span class="score-pill">${escapeHtml(finding.severity_score.toFixed(1))} / 10</span>
    </div>
    <h3>${escapeHtml(finding.title || finding.endpoint)}</h3>
    <dl>
      <div><dt>Class</dt><dd>${escapeHtml(prettyClass(finding.vuln_class))}</dd></div>
      <div><dt>Endpoint</dt><dd class="mono">${escapeHtml(finding.endpoint)}</dd></div>
      <div><dt>Confidence</dt><dd>${escapeHtml(finding.confidence.toFixed(2))}</dd></div>
    </dl>
    <h4>Business impact</h4>
    <p>${escapeHtml(finding.business_impact)}</p>
    ${
      finding.poc_curl
        ? `<h4>Reproduction (PoC)</h4><pre>${escapeHtml(finding.poc_curl)}</pre>`
        : ""
    }
    ${renderEvidence(evidence)}
    ${
      finding.remediation
        ? `<h4>Remediation</h4><pre class="wrap">${escapeHtml(finding.remediation)}</pre>`
        : ""
    }
  </article>`;
}

function renderEvidence(evidence: Evidence | undefined): string {
  if (!evidence) return "";
  return `<h4>Evidence</h4>
    <p class="hint">Authorization redacted, as stored by the scanner.</p>
    <p class="kicker">Request</p>
    <pre>${escapeHtml(JSON.stringify(evidence.request, null, 2))}</pre>
    <p class="kicker">Response</p>
    <pre>${escapeHtml(JSON.stringify(evidence.response, null, 2))}</pre>`;
}

function postureParagraph(scan: ScanDetail, score: number, label: string): string {
  const target = scan.target;
  const total = scan.summary.total_findings;
  if (total === 0) {
    return `SentinelAPI scanned ${target} and recorded no findings. The overall risk score is ${score.toFixed(1)}/10 (${label}). This advisory report reflects the stored scan results only.`;
  }
  const mix = ["Critical", "High", "Medium", "Low"]
    .filter((name) => (scan.summary.by_severity[name] ?? 0) > 0)
    .map((name) => `${scan.summary.by_severity[name]} ${name}`)
    .join(", ");
  const classes = Object.entries(scan.summary.by_vuln_class)
    .map(([name, count]) => `${prettyClass(name)} (${count})`)
    .join(", ");
  return `SentinelAPI scanned ${target} and recorded ${total} finding${total === 1 ? "" : "s"} with an overall risk score of ${score.toFixed(1)}/10 (${label}). Severity mix: ${mix}. Classes flagged: ${classes}. This advisory report uses the stored, rule-based findings only.`;
}

function badge(label: string): string {
  const color = severityColor(label);
  return `<span class="badge" style="color:${color};border-color:${color}33;background:${color}14">${escapeHtml(label)}</span>`;
}

function severityColor(label: string): string {
  return SEVERITY_COLORS[label] ?? SEVERITY_COLORS.Low;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

const REPORT_CSS = `
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body {
    margin: 0 auto;
    max-width: 800px;
    padding: 36px 40px 48px;
    background: #ffffff;
    color: #1a1d24;
    font-family: "IBM Plex Sans", "Segoe UI", system-ui, -apple-system, sans-serif;
    font-size: 14.5px;
    line-height: 1.55;
  }
  h1 { margin: 4px 0 0; font-size: 22px; letter-spacing: -0.02em; }
  h2 {
    margin: 32px 0 12px;
    padding-bottom: 6px;
    border-bottom: 1px solid #e4e7ec;
    font-size: 13px;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #5c6570;
  }
  h3 { margin: 8px 0 10px; font-size: 17px; }
  h4 { margin: 16px 0 6px; font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; color: #5c6570; }
  p { margin: 0 0 10px; }
  .masthead { margin-bottom: 8px; }
  .brand { display: flex; align-items: center; gap: 10px; margin-bottom: 14px; }
  .wordmark { margin: 0; font-size: 12px; font-weight: 600; letter-spacing: 0.04em; }
  .advisory { color: #5c6570; font-size: 13px; }
  .meta { margin: 0 0 4px; color: #5c6570; font-size: 13px; }
  .mono { font-family: "IBM Plex Mono", ui-monospace, "SFMono-Regular", Menlo, monospace; font-size: 12.5px; }
  .kicker { margin: 0 0 8px; font-size: 11px; font-weight: 600; letter-spacing: 0.12em; text-transform: uppercase; color: #5c6570; }
  .summary-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; align-items: start; }
  .score-card { padding: 16px 18px; border: 1px solid #e4e7ec; border-radius: 10px; }
  .score-line { display: flex; align-items: baseline; gap: 8px; margin: 0 0 8px; }
  .hero { font-size: 48px; font-weight: 700; letter-spacing: -0.03em; line-height: 1; }
  .over { color: #5c6570; font-size: 16px; }
  .posture { margin-top: 16px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { padding: 8px 10px; border-bottom: 1px solid #eef0f3; text-align: left; }
  th { font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; color: #5c6570; font-weight: 600; }
  .num { font-variant-numeric: tabular-nums; text-align: right; }
  .badge {
    display: inline-block;
    padding: 2px 8px;
    border: 1px solid;
    border-radius: 4px;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.06em;
    text-transform: uppercase;
  }
  .score-pill { font-variant-numeric: tabular-nums; font-family: ui-monospace, Menlo, monospace; font-size: 13px; color: #5c6570; }
  .block {
    margin: 0 0 16px;
    padding: 16px 18px 18px;
    border: 1px solid #e4e7ec;
    border-radius: 10px;
    break-inside: avoid;
    page-break-inside: avoid;
  }
  .row { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
  dl { display: grid; gap: 8px; margin: 0 0 8px; }
  dt { font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; color: #5c6570; }
  dd { margin: 0; }
  pre {
    margin: 0;
    padding: 12px 14px;
    background: #f6f7f9;
    border-radius: 8px;
    overflow: auto;
    font-family: "IBM Plex Mono", ui-monospace, Menlo, monospace;
    font-size: 12px;
    line-height: 1.45;
    white-space: pre;
  }
  pre.wrap { white-space: pre-wrap; }
  .hint { margin: 0 0 8px; color: #5c6570; font-size: 12px; }
  .empty { color: #5c6570; }
  footer {
    margin-top: 36px;
    padding-top: 14px;
    border-top: 1px solid #e4e7ec;
    color: #5c6570;
    font-size: 12px;
  }
  footer p { margin: 0 0 4px; }
  @page { margin: 16mm; }
  @media print {
    body { max-width: none; padding: 0; }
    .block, .score-card { break-inside: avoid; page-break-inside: avoid; }
  }
  @media (max-width: 640px) {
    body { padding: 24px 18px; }
    .summary-grid { grid-template-columns: 1fr; }
  }
`;
